# Generated by Django 2.1.2 on 2018-10-31 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_count', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='F:\\La Trobe\\Sem 4\\Project\\CodeBase\\Django\\data/images')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('vase_num', models.IntegerField(default=-1, primary_key=True, serialize=False, unique=True)),
                ('fabric', models.CharField(default='South Italian', max_length=100)),
                ('technique', models.CharField(default='Red-Figure', max_length=100)),
                ('shape_name', models.CharField(default='NULL', max_length=100)),
                ('provenance', models.CharField(default='NULL', max_length=100)),
                ('date_range', models.CharField(default='450-300 BC', max_length=100)),
                ('collection', models.CharField(default='NULL', max_length=100)),
                ('scholor_name', models.CharField(default='A.D.Trendall', max_length=100)),
                ('publication', models.CharField(default='The Red Figure Vases of Paestum, Rome 1987', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homePage.Record'),
        ),
    ]
