# Generated by Django 2.1.2 on 2018-10-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='RecordImage',
        ),
    ]
