# Generated by Django 2.1.2 on 2018-11-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20181031_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordimage',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='homePage.Record'),
        ),
    ]
